### ISSUE TITLE
limit feature returning an empty dataframe

### ISSUE THREAD

**Issue by YannOrieult-EngieDigital** [delta-io/delta-sharing#101] opened 2021-12-17 09:10 UTC
The delta_sharing limit feature doesn't seem to work properly. It returns an empty dataframe.

`table = delta_sharing.load_as_pandas(table_url, limit=10)`

```
Empty DataFrame
Columns: [a, b, c, ...]
Index: []
```

**Comment by zsxwing** [comment] 2021-12-17 19:22
Could you elaborate and maybe provide a reproduction?

I did a quick test using our open server (You can run the code as well) and it returned correct results:
```
>>> import delta_sharing
>>> table_url = "https://databricks-datasets-oregon.s3-us-west-2.amazonaws.com/delta-sharing/share/open-datasets.share#delta_sharing.default.owid-covid-data"
>>> data = delta_sharing.load_as_pandas(table_url, limit=10)
>>> print(data)
  iso_code      continent location        date  total_cases  new_cases  ...  female_smokers  male_smokers  handwashing_facilities  hospital_beds_per_thousand  life_expectancy  human_development_index
0      CHL  South America    Chile  2021-03-27     969913.0     7592.0  ...            34.2          41.5                     NaN                        2.11            80.18                    0.851
1      CHL  South America    Chile  2021-03-28     977243.0     7330.0  ...            34.2          41.5                     NaN                        2.11            80.18                    0.851
2      CHL  South America    Chile  2021-03-29     984484.0     7241.0  ...            34.2          41.5                     NaN                        2.11            80.18                    0.851
3      CHL  South America    Chile  2021-03-30     989492.0     5008.0  ...            34.2          41.5                     NaN                        2.11            80.18                    0.851
4      CHL  South America    Chile  2021-03-31     995538.0     6046.0  ...            34.2          41.5                     NaN                        2.11            80.18                    0.851
5      CHL  South America    Chile  2021-04-01    1003406.0     7868.0  ...            34.2          41.5                     NaN                        2.11            80.18                    0.851
6      CHL  South America    Chile  2021-04-02    1011485.0     8079.0  ...            34.2          41.5                     NaN                        2.11            80.18                    0.851
7      CHL  South America    Chile  2021-04-03    1019478.0     7993.0  ...            34.2          41.5                     NaN                        2.11            80.18                    0.851
8      CHL  South America    Chile  2021-04-04    1026785.0     7307.0  ...            34.2          41.5                     NaN                        2.11            80.18                    0.851
9      CHL  South America    Chile  2021-04-05    1032612.0     5827.0  ...            34.2          41.5                     NaN                        2.11            80.18                    0.851

[10 rows x 59 columns]
>>> data0 = delta_sharing.load_as_pandas(table_url, limit=0)
>>> print(data0)
Empty DataFrame
Columns: [iso_code, continent, location, date, total_cases, new_cases, new_cases_smoothed, total_deaths, new_deaths, new_deaths_smoothed, total_cases_per_million, new_cases_per_million, new_cases_smoothed_per_million, total_deaths_per_million, new_deaths_per_million, new_deaths_smoothed_per_million, reproduction_rate, icu_patients, icu_patients_per_million, hosp_patients, hosp_patients_per_million, weekly_icu_admissions, weekly_icu_admissions_per_million, weekly_hosp_admissions, weekly_hosp_admissions_per_million, new_tests, total_tests, total_tests_per_thousand, new_tests_per_thousand, new_tests_smoothed, new_tests_smoothed_per_thousand, positive_rate, tests_per_case, tests_units, total_vaccinations, people_vaccinated, people_fully_vaccinated, new_vaccinations, new_vaccinations_smoothed, total_vaccinations_per_hundred, people_vaccinated_per_hundred, people_fully_vaccinated_per_hundred, new_vaccinations_smoothed_per_million, stringency_index, population, population_density, median_age, aged_65_older, aged_70_older, gdp_per_capita, extreme_poverty, cardiovasc_death_rate, diabetes_prevalence, female_smokers, male_smokers, handwashing_facilities, hospital_beds_per_thousand, life_expectancy, human_development_index]
Index: []
>>> data1 = delta_sharing.load_as_pandas(table_url, limit=1)
>>> print(data1)
  iso_code      continent location        date  total_cases  new_cases  ...  female_smokers  male_smokers  handwashing_facilities  hospital_beds_per_thousand  life_expectancy  human_development_index
0      CHL  South America    Chile  2021-03-27     969913.0     7592.0  ...            34.2          41.5                     NaN                        2.11            80.18                    0.851

[1 rows x 59 columns]
```

**Comment by yoarch** [comment] 2021-12-21 17:55
I imported on my machine a profile file from the creation of a recipient in the Unity Catalog and use it in the code below.

```
client = delta_sharing.SharingClient(DELTA_SHARING_CONF_PATH)

table_url = DELTA_SHARING_CONF_PATH + f"#share.schema.table"

table = delta_sharing.load_as_pandas(table_url)

df = pd.DataFrame(table)
```

This code returns all the rows (thousands) from this table. However, if I had the limit feature, such as limit=10, it returns an empty frame.
```
Empty DataFrame
Columns: [a, b, c, ...]
Index: []
```

Am I doing something wrong ?

**Comment by zsxwing** [comment] 2021-12-23 08:28
@yoarch Are you able to reproduce the same issue using the command in https://github.com/delta-io/delta-sharing/issues/101#issuecomment-996978368 ? If so, could you provide your pandas and pyarrow versions? You can run the code like this to get versions:

```
>>> import pandas
>>> pandas.__version__
'1.3.4'
>>> import pyarrow
>>> pyarrow.__version__
'6.0.1'
```

**Comment by YannOrieult-EngieDigital** [comment] 2021-12-23 13:14
Sorry, I used a wrong account last message.
My pandas version is `1.3.5` and my pyarrow version is `6.0.1`.

**Comment by zsxwing** [comment] 2021-12-29 08:28
@YannOrieult-EngieDigital I still cannot reproduce it using pandas==1.3.5 and pyarrow==0.6.1. Are you able to reproduce it using the commands I posted in https://github.com/delta-io/delta-sharing/issues/101#issuecomment-996978368 ? If not, this may be a Databricks specific issue. If you can reproduce it in a Databricks notebook, could you create a Databricks support ticket instead? I don't want to ask you to post logs in this public forum since it may contain PII or sensitive information.

**Comment by YannOrieult-EngieDigital** [comment] 2021-12-29 14:23
The code above works indeed.

Also, I tried my code directly in a Notebook and got the same _Empty DataFrame_ return.

Is it a delta sharing server issue ? I am going to send a [request](https://help.databricks.com/s/submitrequest) then.

**Comment by zsxwing** [comment] 2022-01-24 23:49
Thanks for raising the issue and providing the details. Closing this as this is a Databricks only issue. This should be fixed now in Databricks. Please reach the Databricks support if the issue still exists.

**Closed by zsxwing** 2022-01-24 23:49 UTC
